"""002_scenario_cascade_deletes

Revision ID: 4d1f291325bc
Revises: edfea3120073
Create Date: 2026-07-29 15:11:26.790356

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d1f291325bc"
down_revision: str | Sequence[str] | None = "edfea3120073"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_runs_scenario_id_scenarios"), "runs", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_runs_scenario_id_scenarios"),
        "runs",
        "scenarios",
        ["scenario_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(op.f("fk_scenarios_suite_id_suites"), "scenarios", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_scenarios_suite_id_suites"),
        "scenarios",
        "suites",
        ["suite_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_scenarios_suite_id_suites"), "scenarios", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_scenarios_suite_id_suites"), "scenarios", "suites", ["suite_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_runs_scenario_id_scenarios"), "runs", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_runs_scenario_id_scenarios"), "runs", "scenarios", ["scenario_id"], ["id"]
    )
    # ### end Alembic commands ###
