"""014_metric_backtests

Revision ID: a08eae7ae4cd
Revises: f72f7f38d74a
Create Date: 2026-09-28 18:09:14.069209

B2.7-10: `metric_backtests` -- one row per backtest run, binding a
`spec_hash` (sha256 of the metric's `spec` jsonb at backtest time) so
PATCH status=active can check "was *this exact spec* backtested" rather
than "was this metric ever backtested at all" (draft edits don't bump
`version`, only PATCH-on-active does, so version alone can't answer that).

Autogenerate again proposed dropping the same 5 pre-existing spurious
indexes noted since migration 010's docstring (ix_agents_project_id and
friends) -- still unrelated drift, still left alone.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a08eae7ae4cd"
down_revision: str | Sequence[str] | None = "f72f7f38d74a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metric_backtests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("metric_id", sa.Uuid(), nullable=False),
        sa.Column("spec_hash", sa.Text(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column(
            "filters", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("agreement", sa.Float(), nullable=True),
        sa.Column("labeled_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "cost", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("created_by_user_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["metrics.id"],
            name=op.f("fk_metric_backtests_metric_id_metrics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_backtests")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metric_backtests")
    # ### end Alembic commands ###
