"""001 initial schema

Revision ID: edfea3120073
Revises:
Create Date: 2026-07-28 17:25:25.122899

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "edfea3120073"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("transport", sa.Text(), nullable=False),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("max_concurrency", sa.Integer(), server_default="1", nullable=False),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "transport IN ('web', 'sip', 'phone')", name=op.f("ck_agents_transport_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
    )
    op.create_table(
        "personas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("voice", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column("accent", sa.Text(), nullable=True),
        sa.Column(
            "traits", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("builtin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_personas")),
    )
    op.create_table(
        "suites",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_suites_agent_id_agents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suites")),
    )
    op.create_table(
        "scenarios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("suite_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("persona", sa.Text(), nullable=False),
        sa.Column("persona_initials", sa.Text(), nullable=False),
        sa.Column("script", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "assertions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_draft_ref", sa.Text(), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'discovery_draft')", name=op.f("ck_scenarios_source_valid")
        ),
        sa.ForeignKeyConstraint(
            ["suite_id"], ["suites.id"], name=op.f("fk_scenarios_suite_id_suites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenarios")),
        sa.UniqueConstraint("source_draft_ref", name=op.f("uq_scenarios_source_draft_ref")),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("scenario_id", sa.Uuid(), nullable=True),
        sa.Column("parent_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Text(), nullable=False),
        sa.Column("claimed_by", sa.Text(), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'claimed', 'running', 'completed', 'cancelled', 'failed')",
            name=op.f("ck_runs_status_valid"),
        ),
        sa.CheckConstraint(
            "type IN ('simulation', 'discovery', 'redteam', 'suite')",
            name=op.f("ck_runs_type_valid"),
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], name=op.f("fk_runs_agent_id_agents")),
        sa.ForeignKeyConstraint(
            ["parent_run_id"], ["runs.id"], name=op.f("fk_runs_parent_run_id_runs")
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"], ["scenarios.id"], name=op.f("fk_runs_scenario_id_scenarios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_runs_idempotency_key")),
    )
    op.create_table(
        "assertion_results",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("assertion_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("triggered_at_turn", sa.Integer(), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.CheckConstraint(
            "status IN ('passed', 'failed')", name=op.f("ck_assertion_results_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_assertion_results_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("run_id", "assertion_id", name=op.f("pk_assertion_results")),
    )
    op.create_table(
        "discovery_drafts",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("persona", sa.Text(), nullable=False),
        sa.Column(
            "assertions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("added_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.ForeignKeyConstraint(
            ["added_scenario_id"],
            ["scenarios.id"],
            name=op.f("fk_discovery_drafts_added_scenario_id_scenarios"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_discovery_drafts_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("run_id", "draft_id", name=op.f("pk_discovery_drafts")),
    )
    op.create_table(
        "discovery_intents",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.CheckConstraint(
            "state <> 'blocked' OR reason IS NOT NULL",
            name=op.f("ck_discovery_intents_reason_required"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_discovery_intents_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("run_id", "name", name=op.f("pk_discovery_intents")),
    )
    op.create_table(
        "discovery_nodes",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("blocked_reason", sa.Text(), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.CheckConstraint(
            "state <> 'blocked' OR blocked_reason IS NOT NULL",
            name=op.f("ck_discovery_nodes_blocked_reason_required"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_discovery_nodes_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("run_id", "node_id", name=op.f("pk_discovery_nodes")),
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("verdict", sa.Text(), nullable=False),
        sa.Column("attack_prompt", sa.Text(), nullable=False),
        sa.Column("agent_response", sa.Text(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("suggested_fix", sa.Text(), nullable=False),
        sa.Column("turn_refs", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verdict = 'blocked' OR evidence IS NOT NULL",
            name=op.f("ck_findings_evidence_required"),
        ),
        sa.CheckConstraint(
            "verdict IN ('blocked', 'leaked', 'bypassed')", name=op.f("ck_findings_verdict_valid")
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_findings_run_id_runs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    op.create_table(
        "run_events",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_run_events_run_id_runs")),
        sa.PrimaryKeyConstraint("run_id", "seq", name=op.f("pk_run_events")),
    )
    op.create_table(
        "turns",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("flagged", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("flag_reason", sa.Text(), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.CheckConstraint("role IN ('caller', 'agent')", name=op.f("ck_turns_role_valid")),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_turns_run_id_runs")),
        sa.PrimaryKeyConstraint("run_id", "idx", name=op.f("pk_turns")),
    )
    op.create_table(
        "discovery_edges",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("from_node", sa.Text(), nullable=False),
        sa.Column("to_node", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id", "from_node"],
            ["discovery_nodes.run_id", "discovery_nodes.node_id"],
            name="fk_discovery_edges_from_node_discovery_nodes",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "to_node"],
            ["discovery_nodes.run_id", "discovery_nodes.node_id"],
            name="fk_discovery_edges_to_node_discovery_nodes",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_discovery_edges_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("run_id", "from_node", "to_node", name=op.f("pk_discovery_edges")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("discovery_edges")
    op.drop_table("turns")
    op.drop_table("run_events")
    op.drop_table("findings")
    op.drop_table("discovery_nodes")
    op.drop_table("discovery_intents")
    op.drop_table("discovery_drafts")
    op.drop_table("assertion_results")
    op.drop_table("runs")
    op.drop_table("scenarios")
    op.drop_table("suites")
    op.drop_table("personas")
    op.drop_table("agents")
    # ### end Alembic commands ###
