"""013_metrics_crud

Revision ID: f72f7f38d74a
Revises: 4acc633493ff
Create Date: 2026-09-27 17:40:18.449795

B2.7-04: metrics CRUD + resolution mechanism. `metrics.project_id` becomes
nullable (a built-in metric, `builtin=true`, has NULL project_id/agent_id
and is read-only project-wide -- same convention as `personas.project_id`);
new `metric_results` table (one row per (run, metric), the metric's final
materialized verdict -- same shape as `assertion_results`, not a per-turn
log). No builtin *rows* are inserted here -- that's B2.7-05's job
(content); this ticket only builds the mechanism a nullable-project_id
builtin row would participate in.

Autogenerate didn't pick up two hand-written changes, added below:
  - the new `builtin_scope_valid` CHECK (it doesn't diff CHECK constraint
    bodies, only presence/absence by name -- this one's new so it wasn't
    missed, but it also never proposed one, since Alembic's constraint
    comparison plugin doesn't compare `CheckConstraint` SQL text at all).
  - `uq_metrics_project_name_no_agent`'s predicate changing from
    `agent_id IS NULL` to `NOT builtin AND agent_id IS NULL` (a builtin
    row now also has `agent_id IS NULL`, so the old predicate would have
    let a builtin collide with a real project-level metric of the same
    name in this index) -- Alembic doesn't diff index predicate text
    either, only presence/absence by name.

Also stripped the same 5 pre-existing spurious index-drop proposals noted
in every migration since 010 (ix_agents_project_id and friends) -- still a
model/DB drift unrelated to this ticket, still left alone.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f72f7f38d74a"
down_revision: str | Sequence[str] | None = "4acc633493ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metric_results",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("metric_id", sa.Uuid(), nullable=False),
        sa.Column("metric_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("turn_refs", sa.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("org_id", sa.Text(), server_default="org_default", nullable=False),
        sa.CheckConstraint(
            "status IN ('passed', 'failed', 'warn', 'error', 'not_sampled', 'not_computable')",
            name=op.f("ck_metric_results_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["metric_id"], ["metrics.id"], name=op.f("fk_metric_results_metric_id_metrics")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_metric_results_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("run_id", "metric_id", name=op.f("pk_metric_results")),
    )
    op.add_column(
        "metrics", sa.Column("builtin", sa.Boolean(), server_default="false", nullable=False)
    )
    op.alter_column("metrics", "project_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(
        "uq_metrics_builtin_name", "metrics", ["name"], unique=True, postgresql_where="builtin"
    )
    # Predicate change, not addition -- see module docstring. Drop the old
    # index (created by migration 010 as "agent_id IS NULL") and recreate
    # it with `builtin` excluded.
    op.drop_index("uq_metrics_project_name_no_agent", table_name="metrics")
    op.create_index(
        "uq_metrics_project_name_no_agent",
        "metrics",
        ["project_id", "name"],
        unique=True,
        postgresql_where="NOT builtin AND agent_id IS NULL",
    )
    op.create_check_constraint(
        "ck_metrics_builtin_scope_valid",
        "metrics",
        "(builtin AND project_id IS NULL AND agent_id IS NULL) "
        "OR (NOT builtin AND project_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_metrics_builtin_scope_valid", "metrics", type_="check")
    op.drop_index("uq_metrics_project_name_no_agent", table_name="metrics")
    op.create_index(
        "uq_metrics_project_name_no_agent",
        "metrics",
        ["project_id", "name"],
        unique=True,
        postgresql_where="agent_id IS NULL",
    )
    op.drop_index("uq_metrics_builtin_name", table_name="metrics", postgresql_where="builtin")
    op.alter_column("metrics", "project_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("metrics", "builtin")
    op.drop_table("metric_results")
    # ### end Alembic commands ###
